import os

MUSICAI = os.path.join('musicai', "")
DATA = os.path.join(MUSICAI, 'data', "")
RAW = os.path.join(DATA, "raw", "")
MAIN = os.path.join(MUSICAI, "main", "")
PREPROCESSING = os.path.join(MAIN, "preprocessing", "")
PROCESSED = os.path.join(DATA, "processed", "")
CHORDS = os.path.join(DATA, "chords", "")
PROCESSED_CHORDS = os.path.join(DATA, 'processed_chords', "")
PROCESSED_CHORDS_MULTI_OCTAVE = os.path.join(DATA, 'processed_chords_multi_octave', "")
PROCESSED_CHORDS_MULTI_OCTAVE_SONG_SPLIT_TRAIN = os.path.join(DATA, 'processed_chords_multi_octave_song_split_train', '')
PROCESSED_CHORDS_MULTI_OCTAVE_SONG_SPLIT_TEST = os.path.join(DATA, 'processed_chords_multi_octave_song_split_test', '')
PROCESSED_CHORDS_RHYMES = os.path.join(DATA, 'processed_chords_rhymes', "")
PICKLES = os.path.join(MAIN, "pickles", "")
MODELS = os.path.join(MAIN, "models", "")